package com.horsefire.gwtamp.server;

/**
 * This is just a list of files in src/main/webapp. It should be generated by
 * the release in the future.
 */
public class FileList {

	public static final String[] FILES = new String[] { "main.css",
			"security.php", "includes/apiMain.php", "includes/common.php",
			"includes/DBManager.php", "includes/GwtSharedConstants.php",
			"includes/LocalConstants.php",
			"includes/ServerConstants.sample.php" };

	/**
	 * Directories to create before copying files
	 */
	public static final String[] DIRS = new String[] { "includes" };
}
